#!/bin/bash
cd ~/git/corefx
rm -rf ./bin/tests/Linux.AnyCPU.Release/System.Net.Security.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Release/System.Net.NetworkInformation.WinRT.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Release/System.Net.NetworkInformation.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Release/System.IO.FileSystem.Watcher.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Private.Uri.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Primitives.UnitTests.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Requests.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Security.Cryptography.Algorithms.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Ping.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Primitives.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Globalization.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Security.Cryptography.X509Certificates.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Http.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Sockets.Async.Performance.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/Common.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.IO.MemoryMappedFiles.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Runtime.InteropServices.RuntimeInformation.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Runtime.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.NameResolution.Pal.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Primitives.Pal.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Diagnostics.Debug.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Diagnostics.TraceSource.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/Microsoft.Win32.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Http.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Diagnostics.FileVersionInfo.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.IO.Compression.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Security.Cryptography.Encoding.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.IO.FileSystem.DriveInfo.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Sockets.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.NameResolution.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.WebSockets.Client.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.IO.Pipes.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.IO.FileSystem.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Private.Uri.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Text.Encoding.CodePages.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Security.Cryptography.OpenSsl.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Debug/System.Net.Security.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Private.Uri.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Primitives.UnitTests.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Requests.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.Algorithms.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Ping.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Primitives.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Globalization.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.X509Certificates.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Http.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Sockets.Async.Performance.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/Common.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.IO.MemoryMappedFiles.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Runtime.InteropServices.RuntimeInformation.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Runtime.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.NameResolution.Pal.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Primitives.Pal.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Diagnostics.Debug.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Diagnostics.TraceSource.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/Microsoft.Win32.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Http.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Diagnostics.FileVersionInfo.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.IO.Compression.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.Encoding.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.IO.FileSystem.DriveInfo.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Sockets.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.NameResolution.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.WebSockets.Client.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.IO.Pipes.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.IO.FileSystem.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Private.Uri.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Text.Encoding.CodePages.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.OpenSsl.Tests/dnxcore50
rm -rf ./bin/tests/Unix.AnyCPU.Release/System.Net.Security.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Debug/System.Net.Security.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Debug/System.Net.NetworkInformation.WinRT.Unit.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Debug/System.Net.NetworkInformation.Functional.Tests/dnxcore50
rm -rf ./bin/tests/Linux.AnyCPU.Debug/System.IO.FileSystem.Watcher.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ValueTuple.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Security.Cryptography.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Numerics.Vectors.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.CustomReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.Streaming.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Linq.Parallel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Net.WebHeaderCollection.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Composition.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.xNodeBuilder.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Text.Encodings.Web.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Linq.Queryable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Linq.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Context.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Serialization.Json.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.Contracts.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlReader.ReadContentAs.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Tasks.Dataflow.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.TreeManipulation.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.InteropServices.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Buffers.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlWriterApi.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.ReaderSettings.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XPath.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.Events.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Collections.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Tasks.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.IO.UnmanagedMemoryStream.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Tasks.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlConvert.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Data.SqlClient.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.DiagnosticSource.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Emit.ILGeneration.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.InteropServices.PInvoke.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ComponentModel.TypeConverter.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.SubtreeReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Resources.ResourceManager.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.TypeExtensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.Axes.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Text.Encoding.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Metadata.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Net.WebSockets.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Linq.Expressions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ComponentModel.Annotations.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.DispatchProxy.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Emit.Lightweight.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Globalization.Calendars.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.SDMSample.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Numerics.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlWriter.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Loader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Data.Common.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Security.Claims.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.TextWriterTraceListener.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.IO.Compression.ZipFile.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Collections.Immutable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Resources.Writer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Collections.Specialized.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Handles.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XmlDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.Misc.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Drawing.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.Tools.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Collections.Concurrent.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XPath.XmlDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.xNodeReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XDocument.Properties.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.Emit.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Text.RegularExpressions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.Process.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Diagnostics.Tracing.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.IO.FileSystem.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.NameTable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ComponentModel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.AppContext.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Collections.NonGeneric.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XmlSerializer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ObjectModel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Loader.DefaultContext.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.TypeExtensions.CoreCLR.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Serialization.Xml.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Tasks.Parallel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.CharCheckingReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Security.SecureString.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Threading.Timer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Reflection.CoreCLR.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Globalization.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Dynamic.Runtime.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/Microsoft.CSharp.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Resources.Reader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.FactoryReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Console.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Data.SqlClient.ManualTesting.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlSystemPathResolver.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Text.Encoding.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.RwFactory.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ComponentModel.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.XPath.XDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.IO.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.IO.Packaging.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.ComponentModel.EventBasedAsync.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Composition.Convention.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Runtime.Serialization.Formatters.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Release/System.Xml.RW.WrappedReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ValueTuple.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Security.Cryptography.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Numerics.Vectors.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.CustomReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.Streaming.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Parallel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Net.WebHeaderCollection.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Composition.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.xNodeBuilder.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Text.Encodings.Web.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Queryable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Context.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Serialization.Json.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.Contracts.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlReader.ReadContentAs.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Dataflow.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.TreeManipulation.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.InteropServices.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Buffers.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlWriterApi.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.ReaderSettings.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XPath.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.Events.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Collections.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.IO.UnmanagedMemoryStream.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlConvert.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Data.SqlClient.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.DiagnosticSource.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Emit.ILGeneration.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.InteropServices.PInvoke.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ComponentModel.TypeConverter.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.SubtreeReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Resources.ResourceManager.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.TypeExtensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.Axes.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Text.Encoding.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Metadata.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Net.WebSockets.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Linq.Expressions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ComponentModel.Annotations.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.DispatchProxy.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Emit.Lightweight.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Globalization.Calendars.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.SDMSample.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Numerics.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlWriter.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Loader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Data.Common.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Security.Claims.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.TextWriterTraceListener.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.IO.Compression.ZipFile.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Collections.Immutable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Resources.Writer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Collections.Specialized.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Handles.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XmlDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.Misc.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Drawing.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.Tools.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Collections.Concurrent.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XPath.XmlDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.xNodeReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XDocument.Properties.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.Emit.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Text.RegularExpressions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.Process.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Diagnostics.Tracing.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.IO.FileSystem.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.NameTable.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ComponentModel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.AppContext.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Collections.NonGeneric.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ObjectModel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Loader.DefaultContext.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.TypeExtensions.CoreCLR.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Serialization.Xml.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Tasks.Parallel.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.CharCheckingReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Security.SecureString.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Threading.Timer.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Reflection.CoreCLR.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Globalization.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Dynamic.Runtime.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Resources.Reader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.FactoryReader.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Console.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Data.SqlClient.ManualTesting.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.XmlSystemPathResolver.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Text.Encoding.Extensions.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.RwFactory.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ComponentModel.Primitives.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.XPath.XDocument.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.IO.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.IO.Packaging.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.ComponentModel.EventBasedAsync.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Composition.Convention.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Runtime.Serialization.Formatters.Tests/dnxcore50
rm -rf ./bin/tests/AnyOS.AnyCPU.Debug/System.Xml.RW.WrappedReader.Tests/dnxcore50
